version: '3'

services:
  read:
    build: .
    ports:
      - "4000:4000"
    environment:
      - MONGO_URI=mongodb://mongo2:27017/myotherdatabase
      - WEATHER_API_KEY=eab290b649b641d1a2b114914232103
      - WEATHER_API=http://api.weatherapi.com/v1/current.json?key=eab290b649b641d1a2b114914232103&q=
    depends_on:
      - mongo4
  mongo2:
    image: mongo:latest
    container_name: mongo2
    ports:
      - "27016:27017"
