version: '3'

services:
  read:
    build: .
    ports:
      - "4000:4000"
    environment:
      - MONGO_URI=mongodb://mongo2:27017/myotherdatabase
      - WEATHER_API_KEY=eab290b649b641d1a2b114914232103
      - WEATHER_API=http://api.weatherapi.com/v1/current.json?key=eab290b649b641d1a2b114914232103&q=
    depends_on:
      - mongo4
  mongo2:
    image: mongo:latest
    container_name: mongo2
    ports:
      - "27016:27017"


# version: '3'
# services:
#   read:
#     build: ./read-server
#     ports:
#       - "3000:3000"
#     environment:
#       - MONGO_URI=mongodb://mongo2:27017/mydb
#       - WEATHER_API_KEY=eab290b649b641d1a2b114914232103
#       - WEATHER_API=http://api.weatherapi.com/v1/current.json?key=eab290b649b641d1a2b114914232103&q=
#     depends_on:
#       - mongo2
#   mongo2:
#     image: mongo:latest
#     ports:
#       - "27017:27017"

#   write:
#     build: ./write-server
#     ports:
#       - "4000:4000"
#     environment:
#       - MONGO_URI=mongodb://mongo:27018/mydb
#       - WEATHER_API_KEY=eab290b649b641d1a2b114914232103
#       - WEATHER_API=http://api.weatherapi.com/v1/current.json?key=eab290b649b641d1a2b114914232103&q=
#     depends_on:
#       - mongo
#   mongo:
#     image: mongo:latest
#     ports:
#       - "27018:27018"
# version: '3'

# services:
#   read:
#     build: ./read-server
#     ports:
#       - "3000:3000"
#     environment:
#       - MONGO_URI=mongodb://mongo2:27018/mydb_read
#       - WEATHER_API_KEY=eab290b649b641d1a2b114914232103
#       - WEATHER_API=http://api.weatherapi.com/v1/current.json?key=eab290b649b641d1a2b114914232103&q=
#     depends_on:
#       - mongo2
#   mongo2:
#     image: mongo
#     ports:
#       - "27018:27018"

#   write:
#     build: ./write-server
#     ports:
#       - "4000:4000"
#     environment:
#       - MONGO_URI=mongodb://mongo1:27017/mydb_write
#       - WEATHER_API_KEY=eab290b649b641d1a2b114914232103
#       - WEATHER_API=http://api.weatherapi.com/v1/current.json?key=eab290b649b641d1a2b114914232103&q=
#     depends_on:
#       - mongo1
#   mongo1:
#     image: mongo
#     ports:
#       - "27017:27017"


# version: '3'
# services:
#   write_db:
#     image: mongo
#     ports:
#       - "27018:27017"
#     # volumes:
#     #   - ./mongo-write-data:/data/db
#   read_db:
#     image: mongo
#     ports:
#       - "27019:27017"
#     # volumes:
#     #   - ./mongo-read-data:/data/db
#   write_server:
#     build: ./write-server
#     ports:
#       - "4000:4000"
#     depends_on:
#       - write_db
#   read_server:
#     build: ./read-server
#     ports:
#       - "3000:3000"
#     depends_on:
#       - read_db
