apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-demo-pvc
spec:
  storageClassName: longhorn-test
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
